# Generated by Django 3.2.3 on 2021-07-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.FileField(blank=True, upload_to='hugo_users/'),
        ),
    ]
