# Generated by Django 3.2.3 on 2021-07-12 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_requestticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestticket',
            name='ticket',
        ),
        migrations.CreateModel(
            name='TicketAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.IntegerField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket Availability',
                'verbose_name_plural': 'Ticket Availabilities',
                'db_table': 'ticket_availabilities',
            },
        ),
    ]
