# Generated by Django 3.2.3 on 2021-07-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20210712_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketavailability',
            name='ticket',
        ),
    ]
