from .users import UserListCreate,UserDetail,SalaryApi,SalaryDetail
from .employee import EmployeeApi,EmployeeDetail,EmploymentDetail,EmploymentApi,EmployDocsApi,EmployDocsDetail
from .employee import EducationApi,EducationDetail,EducationDocsApi,EducationDocsDetail,InternshipApi,InternshipDetail
from .project import ProjectApi,ProjectDetail
from .library import EventApi,EventDetail,HolidayApi,HolidayDetail
from .ticket import TicketApi,TicketDetail,RequestTicketApi,RequestTicketDetail,TicketAvailabilityApi,TicketAvailabilityDetail