from .users import UserSerializer,SalarySerializer
from .employee import EmployeeSerializer,EmploymentSerializer,EmployDocsSerializer,EducationSerializer
from .employee import EducationDocsSerializer,InternshipSerializer
from .project import ProjectSerializer,ProjectAssigneeSerializer
from .library import EventSerializer,HolidaySerializer
from .ticket import TicketSerializer,RequestTicketSerializer,TicketAvailabilitySerializer
